image: gitpod/workspace-full

tasks:
  - name: Run server
    command: python -m http.server 8000
  - name: Setup environment
    command: |
      echo "setup environment, please wait..."
      if [ -f .vanilla_indicator ]; then
          rm -rf * .[!.]* # clean up workspace
      fi
      echo "alias show-server-url='echo https://0.0.0.0:8000'" >> ~/.bashrc
      source ~/.bashrc &> /tmp/log-source-bashrc.txt
      echo "done, ready to go!"