image: gitpod/workspace-full

tasks:
  - name: Run server
    command: python -m http.server 8000
  - name: Setup environment
    command: |
      echo "setup environment, please wait..."
      rm -rf * .[!.]* # clean up workspace
      ("${SHELL}" <(curl -L micro.mamba.pm/install.sh) < /dev/null) &> /tmp/log-setup-micromamba.txt
      echo "alias show-report-url='echo https://0.0.0.0:8000/example-report'" >> ~/.bashrc
      source ~/.bashrc &> /tmp/log-source-bashrc.txt
      micromamba create -n datavzrd -c conda-forge datavzrd --yes &> /tmp/log-setup-datavzrd.txt
      echo "micromamba activate datavzrd" >> ~/.bashrc
      micromamba activate datavzrd
      echo "done, ready to go!"

vscode:
  extensions:
    - oderwat/indent-rainbow
    - mechatroner/rainbow-csv