[project]
name = "build-env"
version = "0.1.0"
description = "Env fro building sphinx pages"
authors = ["Johannes Koester <johannes.koester@uni-due.de>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
build = "sphinx-build -b html source build/html"

[dependencies]
sphinxawesome-theme = ">=5.2.0,<6"
sphinx-design = ">=0.6.0,<0.7"
sphinx = ">=7.2.6,<8"
